// Code generated by protoc-gen-go. DO NOT EDIT.
// source: websocket/structmessage.proto

/*
Package websocket is a generated protocol buffer package.

It is generated from these files:
	websocket/structmessage.proto

It has these top-level messages:
	StructMessageProtobuf
*/
package websocket

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// StructMessage is a Protobuf based message on top of Message.
// It implements Message interface and can be sent with via a Speaker.
type StructMessageProtobuf struct {
	Namespace string `protobuf:"bytes,1,opt,name=Namespace" json:"Namespace,omitempty"`
	Type      string `protobuf:"bytes,2,opt,name=Type" json:"Type,omitempty"`
	UUID      string `protobuf:"bytes,3,opt,name=UUID" json:"UUID,omitempty"`
	Status    int64  `protobuf:"varint,4,opt,name=Status" json:"Status,omitempty"`
	Obj       []byte `protobuf:"bytes,5,opt,name=Obj,proto3" json:"Obj,omitempty"`
}

func (m *StructMessageProtobuf) Reset()                    { *m = StructMessageProtobuf{} }
func (m *StructMessageProtobuf) String() string            { return proto.CompactTextString(m) }
func (*StructMessageProtobuf) ProtoMessage()               {}
func (*StructMessageProtobuf) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *StructMessageProtobuf) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *StructMessageProtobuf) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *StructMessageProtobuf) GetUUID() string {
	if m != nil {
		return m.UUID
	}
	return ""
}

func (m *StructMessageProtobuf) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *StructMessageProtobuf) GetObj() []byte {
	if m != nil {
		return m.Obj
	}
	return nil
}

func init() {
	proto.RegisterType((*StructMessageProtobuf)(nil), "websocket.StructMessageProtobuf")
}

func init() { proto.RegisterFile("websocket/structmessage.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 163 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2d, 0x4f, 0x4d, 0x2a,
	0xce, 0x4f, 0xce, 0x4e, 0x2d, 0xd1, 0x2f, 0x2e, 0x29, 0x2a, 0x4d, 0x2e, 0xc9, 0x4d, 0x2d, 0x2e,
	0x4e, 0x4c, 0x4f, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x84, 0x4b, 0x2b, 0xb5, 0x33,
	0x72, 0x89, 0x06, 0x83, 0x95, 0xf8, 0x42, 0x94, 0x04, 0x80, 0x54, 0x24, 0x95, 0xa6, 0x09, 0xc9,
	0x70, 0x71, 0xfa, 0x25, 0xe6, 0xa6, 0x16, 0x17, 0x24, 0x26, 0xa7, 0x4a, 0x30, 0x2a, 0x30, 0x6a,
	0x70, 0x06, 0x21, 0x04, 0x84, 0x84, 0xb8, 0x58, 0x42, 0x2a, 0x0b, 0x52, 0x25, 0x98, 0xc0, 0x12,
	0x60, 0x36, 0x48, 0x2c, 0x34, 0xd4, 0xd3, 0x45, 0x82, 0x19, 0x22, 0x06, 0x62, 0x0b, 0x89, 0x71,
	0xb1, 0x05, 0x97, 0x24, 0x96, 0x94, 0x16, 0x4b, 0xb0, 0x28, 0x30, 0x6a, 0x30, 0x07, 0x41, 0x79,
	0x42, 0x02, 0x5c, 0xcc, 0xfe, 0x49, 0x59, 0x12, 0xac, 0x0a, 0x8c, 0x1a, 0x3c, 0x41, 0x20, 0x66,
	0x12, 0x1b, 0xd8, 0x6d, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x5d, 0x57, 0x73, 0x15, 0xbc,
	0x00, 0x00, 0x00,
}
